# Generated by Django 2.1.2 on 2018-11-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Distribuidor',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo_de_documento',
            new_name='documento',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='distribuidor',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='medicamento',
            field=models.ImageField(default=1, upload_to='medicamento/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.Categoria'),
        ),
    ]
