# Generated by Django 2.1.2 on 2018-11-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_auto_20181127_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='tipo',
        ),
    ]
